### PR TITLE
Separate module for output classes

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Review by liamhuber — COMMENTED** [review]
I am definitely happy to move the classes out to their own module and to use it for calc static.

I found this PR to be too verbose, although I think I'm ultimately to blame for this since I introduced `__call__`, which required actually instantiating these classes. I stacked a new PR that replaces `__call__` with a class method `get` which behaves the same way but is accessible right from the class. This lets use remove the `get_*` layer of misdirection functions entirely. As a result, I also directly leverage `.fields()` since I no longer instantiate the classes.

Not addressed in my PR, but something we should think about, is the way the MD output doesn't inherit from the static output. I would suggest renaming `LammpsStaticOutput.energy` to `LammpsStaticOutput.energy_pot`, and then using `LammpsMDOutput(LammpsStaticOutput)` directly. This has the additional effect that stresses can be calcualted in MD -- is this possible? Anyhow, I would like that direction but thought it warranted a second thought before I stacked it on. I suspect @samwaseda will have an opinion on this.

**Review by liamhuber — APPROVED** [review]
With the changes merged in from my stacked PR, I'm happy. I do think we need to address `energy` vs `energy_pot` and would be inclined to get @samwaseda's opinion before merging, but IMO we could merge this and then open an issue on that topic to fix later.

**Comment by jan-janssen** [comment]
I created the issue https://github.com/pyiron/atomistics/issues/129 , still I prefer to have the discussion in https://github.com/pyiron/atomistics/pull/121 rather than keeping this pull request open.

**Comment by liamhuber** [comment]
> I created the issue #129 , still I prefer to have the discussion in #121 rather than keeping this pull request open.

@jan-janssen, now that #129 is open I feel we have cover to merge #121 as well if you want -- with the issue there we won't lose track of its deficiencies, and it's only imperfect not broken. I don't think we _have_ to merge it, but I'm about to be literally unconscious for ~7 hours so I just want you to know I'm not standing in the way 😂

**Comment by jan-janssen** [comment]
> @jan-janssen, now that #129 is open I feel we have cover to merge #121 as well if you want 

I agree, I just want to give Sam the chance to have a look at it, once he agrees we can merge it.

**Pull request merged**
