### PR TITLE
With a dataclass

### PR DESCRIPTION
**Pull request by liamhuber**
Dammit @jan-janssen, too much [momentum](https://github.com/pyiron/atomistics/pull/118#issuecomment-1850732994)! 😂 

Here it is with @samwaseda's requested changes.

In particular, the actual implementation _instantiates_ the data class and then uses `__call__` magic. We could alternatively remove the `__call__` magic and just use the commented-out `getattr` version that works right on the class.

IMO this is just the first step to abstraction, and it would be nice to see a similar data class actually pushed up and used by multiple calculators, with details of how they take and engine and a quantity name and turn it into a result being left to the children. For now the abstraction inside Lammps is already nice.

### CODE REVIEW

**Comment by jan-janssen** [comment]
I added a stacked pull request in https://github.com/pyiron/atomistics/pull/123 to also use the data class for calc static.

**Comment by samwaseda** [comment]
It’s mostly about naming, but it looks like it’s very much LAMMPS-oriented. I have the feeling that it should be applied to other atomistic codes as well, so maybe we can think about making it look less like it’s only for LAMMPS.

**Comment by jan-janssen** [comment]
> It’s mostly about naming, but it looks like it’s very much LAMMPS-oriented. I have the feeling that it should be applied to other atomistic codes as well, so maybe we can think about making it look less like it’s only for LAMMPS.

I think the scope of the current pull request is to focus on LAMMPS, unifying this and merging it with ASE is again another step from my perspective.

**Comment by liamhuber** [comment]
> I think the scope of the current pull request is to focus on LAMMPS, unifying this and merging it with ASE is again another step from my perspective.

Agreed. I am 100% with Sam on want to make this attack more generic, but IMO we can do name changes to facilitate that later.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
@samwaseda : @liamhuber and I converged to this solution, while we agree that it would be great to implement the same functionality for other simulation codes we would prefer to merge this pull request as it is. In addition, there is still another open issue about the naming conventions https://github.com/pyiron/atomistics/issues/129 which again should be addressed in a separate pull request. @samwaseda any objections to merging this/?

**Review by samwaseda — APPROVED** [review]

**Pull request merged**
