### PR TITLE
Update spglib 2.3.0

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
```
======================================================================
ERROR: test_calc_elastic (test_elastic_ase_emt.TestElastic.test_calc_elastic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/atomistics/atomistics/tests/test_elastic_ase_emt.py", line 28, in test_calc_elastic
    task_dict = workflow.generate_structures()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atomistics/atomistics/atomistics/workflows/elastic/workflow.py", line 33, in generate_structures
    self._data, self._structure_dict = generate_structures_helper(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atomistics/atomistics/atomistics/workflows/elastic/helper.py", line 21, in generate_structures_helper
    SGN, v0, LC, Lag_strain_list, epss = symmetry_analysis(
                                         ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atomistics/atomistics/atomistics/workflows/elastic/symmetry.py", line 328, in symmetry_analysis
    SGN = find_symmetry_group_number(structure)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atomistics/atomistics/atomistics/workflows/elastic/symmetry.py", line 6, in find_symmetry_group_number
    dataset = spglib.get_symmetry_dataset(struct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/my-env/lib/python3.12/site-packages/spglib/spglib.py", line 696, in get_symmetry_dataset
    lattice, positions, numbers, _ = _expand_cell(cell)
                                     ^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/my-env/lib/python3.12/site-packages/spglib/spglib.py", line 1985, in _expand_cell
    lattice = np.array(np.transpose(cell[0]), dtype="double", order="C")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'Atom'

----------------------------------------------------------------------
```

**Comment by jan-janssen** [comment]
@samwaseda Can you take a look at this? It seems like the `get_symmetry_dataset()` function in `spglib=2.3.0` no longer accepts `ase.atoms.Atoms` as input?

**Comment by samwaseda** [comment]
It's actually written [here](https://spglib.readthedocs.io/en/latest/releases.html) and [here](https://github.com/spglib/spglib/pull/386)

**Comment by samwaseda** [comment]
Now it should be fine. Can you check the environment file?

**Comment by samwaseda** [comment]
Sorry don't merge it yet

**Comment by jan-janssen** [comment]
> Sorry don't merge it yet

I set the pull request to draft - feel free to set it `ready for review` once you are satisfied.

**Comment by samwaseda** [comment]
Now it should be fine.

**Comment by samwaseda** [comment]
> ```
> ======================================================================
> ERROR: test_calc_elastic (test_elastic_ase_emt.TestElastic.test_calc_elastic)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "D:\a\atomistics\atomistics\tests\test_elastic_ase_emt.py", line 28, in test_calc_elastic
>     task_dict = workflow.generate_structures()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\a\atomistics\atomistics\atomistics\workflows\elastic\workflow.py", line 33, in generate_structures
>     self._data, self._structure_dict = generate_structures_helper(
>                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\a\atomistics\atomistics\atomistics\workflows\elastic\helper.py", line 21, in generate_structures_helper
>     SGN, v0, LC, Lag_strain_list, epss = symmetry_analysis(
>                                          ^^^^^^^^^^^^^^^^^^
>   File "D:\a\atomistics\atomistics\atomistics\workflows\elastic\symmetry.py", line 343, in symmetry_analysis
>     SGN = find_symmetry_group_number(structure)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\a\atomistics\atomistics\atomistics\workflows\elastic\symmetry.py", line 21, in find_symmetry_group_number
>     dataset = spglib.get_symmetry_dataset(cell=ase_to_spglib(struct))
>                                                ^^^^^^^^^^^^^^^^^^^^^
>   File "D:\a\atomistics\atomistics\atomistics\workflows\elastic\symmetry.py", line 14, in ase_to_spglib
>     np.array(cell.get_cell().T, dtype="double", order="C"),
>              ^^^^
> NameError: name 'cell' is not defined
> 
> ----------------------------------------------------------------------
> ```

lol thanks for the correction XD

**Pull request merged**
